yarnPath: .yarn/releases/yarn-4.0.2.cjs

# Yarn Berry's feature PnP node linker isn't supported for React Native.
# Use the traditional `node_modules` folder. Reference: https://yarnpkg.com/features/pnp.
nodeLinker: node-modules

enableGlobalCache: false

enableTelemetry: false
